server:
  port: 8081
  servlet:
    context-path: /user-service

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:user-service-db
    driver-class-name: org.h2.Driver
    username: root
    password: root
    initialization-mode: always

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: localhost:9411

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

connection:
  timeout: 3000

service:
  organization-service:
    base-url: http://localhost:8082/organization-service