server:
  port: 8082
  servlet:
    context-path: /organization-service

spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:organization-service-db
    driver-class-name: org.h2.Driver
    username: root
    password: root